version: "3"
services:
  postgres:
    image: "postgres:12.0"
    container_name: "grog_postgres"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ~/.grog/postgres:/var/lib/postgresql/data
