version: "3"
services:
  postgres:
    image: "postgres:12.0"
    container_name: "grog_postgres"
    environment:
      - POSTGRES_USER=${GROG_POSTGRES_USER}
      - POSTGRES_PASSWORD=${GROG_POSTGRES_PASSWORD}
      - POSTGRES_DB=${GROG_POSTGRES_DB}
    ports:
      - "${GROG_POSTGRES_PORT}:5432"
    volumes:
      - ${GROG_COMPOSE_DIR}/postgres:/var/lib/postgresql/data
